import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const readingNotesSidebar: SidebarsConfig = {
  // 使用自动生成的侧边栏，和documentation一样
  readingNotesSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default readingNotesSidebar;